### ISSUE TITLE
Not Support

### ISSUE THREAD

**Issue by LittleHaoYu** [ProtonGameStudio/ClassroomTool#2]
This app does not fully support Windows 11 (there may be some issues on Windows 11), please fix this quickly!

**Comment by hehe1005566889** [comment]
Can You Upload The Picture Or Tell Me The Problem More Clearly Thanks

**Comment by hehe1005566889** [comment]
I Don't Have Win11 PC xD

**Comment by LittleHaoYu** [comment]
ok,i will try it.

**Comment by hehe1005566889** [comment]
Please Download The Newer Version Later
